### ISSUE TITLE
Pipeline should send information to zafira that zafiraServiceURL, zafiraAccessToken empty

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-pipeline#689] opened 2020-04-07 14:59 UTC
qps-pipeline - 4.10
Steps:
1. Create organization with empty zafiraServiceURL, zafiraAccessToken  fields
2. Create Repository
3. Open zafira app
4. Start Scan repository
Actual result: Scan can't be completed
Expected: Pipeline should send information to zafira that zafiraServiceURL, zafiraAccessToken empty
<img width="1440" alt="Screen Shot 2020-04-07 at 4 31 34 PM" src="https://user-images.githubusercontent.com/32964663/78684735-81e9e280-78f9-11ea-83d1-6bc1d67f21b5.png">

**Comment by hursevich** [comment] 2020-04-09 09:10
Let's poll jenkins job status every 30 seconds and if we get that job is finished and no callback was sent to Zebrunner - then show UI message: Sorry, we were not able to scan the repository, contact support or try again later.

**Comment by vdelendik** [comment] 2020-04-11 14:49
@okamara closing as not a bug.
If user register org/repository without integration with Zafira it doesn't have repo registered in Test Launchers.

In valid use-case when integration is enabled we can re-create launchers successfully from any place (CI or Zafira). Improvement to support negative scanner scenario will be submitted soon.

**Closed by vdelendik** 2020-04-11 14:49 UTC
Labels: bug
